disabled_rules:
  - line_length
  - trailing_whitespace
  - empty_parentheses_with_trailing_closure
  - opening_brace
#   - cyclomatic_complexity
#   - file_length
#   - function_body_length
#   - function_parameter_count
#   - nesting
#   - type_body_length
#   - variable_name

opt_in_rules:
  - vertical_whitespace
  - operator_usage_whitespace
  - outlet_setter

# configurable rules can be customized from this configuration file
# binary rules can set their severity level
force_cast: warning # implicitly
force_try:
  severity: warning # explicitly
type_name:
    min_length: 2
identifier_name:
    min_length: 2
trailing_comma:
    mandatory_comma: false
nesting:
    type_level: 2
excluded:
  - Pods
  - HipstapaperCommon/Tests
