project 'Hipstapaper.xcodeproj'

target 'Hipstapaper_app_macOS' do
  platform :osx, '10.11'
  use_frameworks!
  pod 'RealmSwift'
end

target 'Hipstapaper_app_macOS_tests' do
  platform :osx, '10.11'
  use_frameworks!
  pod 'RealmSwift'
end

# target 'Hipstapaper_share_macOS' do
#   platform :osx, '10.12'
#   use_frameworks!
#   pod 'RealmSwift'
# end

target 'Hipstapaper_app_iOS' do
  platform :ios, '9.0'
  use_frameworks!
  pod 'RealmSwift'
end

# target 'Hipstapaper_share_iOS' do
#   platform :ios, '10.0'
#   use_frameworks!
#   pod 'RealmSwift'
# end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0.2'
    end
  end
end